[package]
name = "ineed"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-session = { version = "0.9", features = ["cookie-session"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"